#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Compress all plain text or markdown logs in logs/dev_sessions/ and generate an index file with links.
Run this script after adding new logs or before a release.
"""

# Metadata
__author__ = ["Andy Turner <agdturner@gmail.com>"]
__version__ = "0.1.0"
__copyright__ = "Copyright (c) 2026 GABM contributors, University of Leeds"

# Standard library imports
import os
import gzip
import shutil
from pathlib import Path

# Constants
LOG_DIR = Path(__file__).parent.parent / "data" / "logs" / "dev_sessions"
INDEX_FILE = LOG_DIR / "index.md"

def compress_logs():
    """
    Compress all .txt and .md files in the LOG_DIR to .gz format.   
    Returns:
        None
    """
    for file in LOG_DIR.iterdir():
        if file.is_file() and file.suffix in {".txt", ".md", ".log"} and not file.name.endswith(".gz"):
            gz_path = file.with_suffix(file.suffix + ".gz")
            with open(file, "rb") as f_in, gzip.open(gz_path, "wb") as f_out:
                shutil.copyfileobj(f_in, f_out)
            print(f"Compressed {file.name} -> {gz_path.name}")
            # Optionally remove original after compression
            # file.unlink()

def generate_index():
    """
    Generate an index.md file in LOG_DIR with links to all .gz files.
    Returns:
        None
    """
    entries = []
    for file in sorted(LOG_DIR.iterdir()):
        if file.suffix == ".gz":
            entries.append(f"- [{file.name}]({file.name})")
    with open(INDEX_FILE, "w") as f:
        f.write("# Compressed Development Session Logs\n\n")
        f.write("This index is auto-generated by scripts/compress_dev_logs.py.\n\n")
        f.write("\n".join(entries))
        f.write("\n")
    print(f"Wrote index: {INDEX_FILE}")

if __name__ == "__main__":
    compress_logs()
    generate_index()
